import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const josefinSans = Josefin_Sans({ 
  weight: ["100","200","300","400" ,"500", "600","700"],
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="body" className={josefinSans.className}>
      <main className="w-full h-screen dark:bg-[#181824] dark:text-white relative flex justify-center">
      <Nav />
      {children}
    </main>
  
      </body>
    </html>
  );
}
